name: PESQ score
on: [push]

jobs:
  test:
    name: Testing (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup packages
        run: |
          $CONDA/bin/conda env update --file environment.yaml --name base
          pip install -e .[tests,docs]

      - name: Run python tests
        run:
          py.test

