name: Testing
on:
  push:
    paths:
      - torch_pesq/**
      - tests/**

jobs:
  test:
    name: Testing (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v1

      - name: Cache samples
        id: cache-samples
        uses: actions/cache@v3
        with:
          path: |
            tests/samples/speech
            tests/samples/noise

          key: ${{ runner.os }}-samples

      - name: Download and extract samples
        if: steps.cache-samples.outputs.cache-hit != 'true'
        run: cd tests/ && ./download_samples

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup packages
        run: |
          pip install -e .[tests]

      - name: Run python tests
        run:
          py.test

